networks:
  bridge:
    driver: bridge

services:
  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    env_file:
      - .env
    networks:
      bridge:
        aliases:
          - zookeeper
  
  kafka:
    image: confluentinc/cp-kafka
    depends_on:
      - zookeeper
    env_file:
      - .env
    networks:
      bridge:
        aliases:
          - kafka

  kafka-producer:
    build:
      context: ./kafka-producer
    container_name: kafka-producer
    depends_on:
      - kafka
      - postgres
      - kafka-consumer
    env_file:
      - .env
    networks:
      - bridge

  kafka-consumer:
    build:
      context: ./kafka-consumer
    container_name: kafka-consumer
    depends_on:
      - kafka
      - postgres
    env_file:
      - .env
    networks:
      - bridge

  # ui:
  #   build:
  #     context: ./ui
  #   container_name: ui
  #   restart: always
  #   ports:
  #     - "8501:8501"
  #   depends_on:
  #     - postgres
  #   env_file:
  #     - .env
  #   networks:
  #     - bridge

  postgres:
    build:
      context: ./postgres
    container_name: postgres
    restart: always
    env_file:
      - .env
    ports:
      - "5432:5432"
    networks:
      - bridge

  pgadmin:
    image: dpage/pgadmin4
    restart: always
    env_file:
      - .env
    ports:
      - "8080:80"
    depends_on:
      - postgres
    networks:
      - bridge

  forex-rates:
    build:
      context: ./forex-rates
    container_name: forex-rates
    restart: always
    env_file:
      - .env
    networks:
      - bridge

volumes:
  settings:
  data: