version: 2

sources:
  - name: postgres
    database: postgres
    schema: public
    tables:
      - name: transactions

models:
  - name: stg_transactions
    description: "Staging table for transactions data"
    columns:
      - name: amount
        data_type: numeric
        description: "Amount of the transaction - 100 = £1"
        data_tests:
          - not_null:
              severity: warn
      - name: amount_captured
        data_type: numeric
        description: "Amount in bani captured (can be less than the amount attribute on the charge if a partial capture was made)"
      - name: amount_refunded
        data_type: numeric
        description: "Amount in bani refunded (can be less than the amount attribute on the charge if a partial refund was issued)"
      - name: application
        data_type: string
        description: "ID of the Connect application that created the charge"
      - name: application_fee
        data_type: numeric
        description: "The application fee (if any) for the charge See the Connect documentation for details"
      - name: application_fee_amount
        data_type: numeric
        description: "The amount of the application fee (if any) requested for the charge See the Connect documentation for details"
      - name: balance_transaction
        data_type: string
        description: "ID of the balance transaction that describes the impact of this charge on your account balance (not including refunds or disputes)"
      - name: billing_details_address_city
        data_type: string
        description: "City in the billing address"
      - name: billing_details_address_country
        data_type: string
        description: "Country in the billing address"
      - name: billing_details_address_line1
        data_type: string
        description: "Line 1 of the billing address"
      - name: billing_details_address_line2
        data_type: string
        description: "Line 2 of the billing address"
      - name: billing_details_address_postal_code
        data_type: string
        description: "Postal code in the billing address"
      - name: billing_details_address_state
        data_type: string
        description: "State in the billing address"
      - name: billing_details_email
        data_type: string
        description: "Email in the billing details"
      - name: billing_details_name
        data_type: string
        description: "Name in the billing details"
      - name: billing_details_phone
        data_type: string
        description: "Phone number in the billing details"
      - name: calculated_statement_descriptor
        data_type: string
        description: "The full statement descriptor that is passed to card networks, and that is displayed on your customers’ credit card and bank statements Allows you to see what the statement descriptor looks like after the static and dynamic portions are combined"
      - name: captured
        data_type: boolean
        description: "If the charge was created without capturing, this Boolean represents whether it is still uncaptured or has since been captured"
      - name: created
        data_type: datetime
        description: "Timestamp of when the transaction was created"
        data_tests:
          - not_null:
              severity: warn
      - name: currency
        data_type: string
        description: "Three-letter ISO currency code, in lowercase Must be a supported currency"
      - name: customer
        data_type: string
        description: "The ID of the customer this charge is for if one exists"
      - name: description
        data_type: string
        description: "An arbitrary string attached to the object Often useful for displaying to users"
      - name: destination
        data_type: string
        description: "Destination of the transaction"
      - name: dispute
        data_type: string
        description: "Dispute associated with the transaction"
      - name: disputed
        data_type: boolean
        description: "Whether the charge has been disputed"
      - name: failure_balance_transaction
        data_type: string
        description: "Balance transaction associated with the failure"
      - name: failure_code
        data_type: string
        description: "Error code explaining reason for charge failure if available (see the errors section for a list of codes)"
      - name: failure_message
        data_type: string
        description: "Message to user further explaining reason for charge failure if available"
      - name: id
        data_type: string
        description: "ID of the transaction"
        data_tests:
          - not_null:
              severity: warn
          - unique:
              severity: warn
      - name: invoice
        data_type: string
        description: "The ID of the invoice this charge is for if one exists"
      - name: livemode
        data_type: boolean
        description: "Has the value true if the object exists in live mode or the value false if the object exists in test mode"
      - name: object
        data_type: string
        description: "String representing the object’s type Objects of the same type share the same value"
      - name: on_behalf_of
        data_type: string
        description: "The account (if any) the charge was made on behalf of without triggering an automatic transfer See the Connect documentation for details"
      - name: order
        data_type: string
        description: "ID of the order this charge is for if one exists"
      - name: outcome_network_status
        data_type: string
        description: "Network status of the transaction outcome"
      - name: outcome_reason
        data_type: string
        description: "Reason for the transaction outcome"
      - name: outcome_risk_level
        data_type: string
        description: "Risk level of the transaction outcome"
      - name: outcome_risk_score
        data_type: numeric
        description: "Risk score of the transaction outcome"
      - name: outcome_seller_message
        data_type: string
        description: "Seller message of the transaction outcome"
      - name: outcome_type
        data_type: string
        description: "Type of the transaction outcome"
      - name: paid
        data_type: boolean
        description: "True if the charge succeeded, or was successfully authorized for later capture"
      - name: payment_intent
        data_type: string
        description: "The ID of the PaymentIntent associated with this charge, if one exists"
      - name: payment_method
        data_type: string
        description: "ID of the payment method used in this charge"
      - name: payment_method_details_card_amount_authorized
        data_type: numeric
        description: "Amount authorized by the card payment method"
      - name: payment_method_details_card_brand
        data_type: string
        description: "Brand of the card payment method"
      - name: payment_method_details_card_checks_address_line1_check
        data_type: string
        description: "Address line 1 check result of the card payment method"
      - name: payment_method_details_card_checks_address_postal_code_check
        data_type: string
        description: "Postal code check result of the card payment method"
      - name: payment_method_details_card_checks_cvc_check
        data_type: string
        description: "CVC check result of the card payment method"
      - name: payment_method_details_card_country
        data_type: string
        description: "Country of the card payment method"
      - name: payment_method_details_card_exp_month
        data_type: integer
        description: "Expiration month of the card payment method"
      - name: payment_method_details_card_exp_year
        data_type: integer
        description: "Expiration year of the card payment method"
      - name: payment_method_details_card_extended_authorization_status
        data_type: string
        description: "Extended authorization status of the card payment method"
      - name: payment_method_details_card_fingerprint
        data_type: string
        description: "Fingerprint of the card payment method"
      - name: payment_method_details_card_funding
        data_type: string
        description: "Funding type of the card payment method"
      - name: payment_method_details_card_incremental_authorization_status
        data_type: string
        description: "Incremental authorization status of the card payment method"
      - name: payment_method_details_card_installments
        data_type: integer
        description: "Number of installments for the card payment method"
      - name: payment_method_details_card_last4
        data_type: string
        description: "Last 4 digits of the card payment method"
      - name: payment_method_details_card_mandate
        data_type: string
        description: "Mandate of the card payment method"
      - name: payment_method_details_card_multicapture_status
        data_type: string
        description: "Multicapture status of the card payment method"
      - name: payment_method_details_card_network
        data_type: string
        description: "Network of the card payment method"
      - name: payment_method_details_card_network_token_used
        data_type: boolean
        description: "Flag indicating if a network token was used with the card payment method"
      - name: payment_method_details_card_overcapture_maximum_amount
        data_type: numeric
        description: "Maximum amount that can be overcaptured with the card payment method"
      - name: payment_method_details_card_overcapture_status
        data_type: string
        description: "Overcapture status of the card payment method"
      - name: payment_method_details_card_three_d_secure
        data_type: string
        description: "3D Secure status of the card payment method"
      - name: payment_method_details_card_wallet
        data_type: string
        description: "Wallet of the card payment method"
      - name: payment_method_details_type
        data_type: string
        description: "Type of the payment method details"
      - name: receipt_email
        data_type: string
        description: "This is the email address that the receipt for this charge was sent to"
      - name: receipt_number
        data_type: string
        description: "This is the transaction number that appears on email receipts sent for this charge This attribute will be null until a receipt has been sent"
      - name: receipt_url
        data_type: string
        description: "This is the URL to view the receipt for this charge The receipt is kept up-to-date to the latest state of the charge, including any refunds If the charge is for an Invoice, the receipt will be stylized as an Invoice receipt"
      - name: refunded
        data_type: boolean
        description: "Whether the charge has been fully refunded If the charge is only partially refunded, this attribute will still be false"
      - name: review
        data_type: string
        description: "ID of the review associated with this charge if one exists"
      - name: shipping
        data_type: string
        description: "Shipping information for the charge"
      - name: source_address_city
        data_type: string
        description: "City in the source address"
      - name: source_address_country
        data_type: string
        description: "Country in the source address"
      - name: source_address_line1
        data_type: string
        description: "Line 1 of the source address"
      - name: source_address_line1_check
        data_type: string
        description: "Address line 1 check result of the source"
      - name: source_address_line2
        data_type: string
        description: "Line 2 of the source address"
      - name: source_address_state
        data_type: string
        description: "State in the source address"
      - name: source_address_zip
        data_type: string
        description: "Zip code in the source address"
      - name: source_address_zip_check
        data_type: string
        description: "Zip code check result of the source"
      - name: source_brand
        data_type: string
        description: "Brand of the source"
      - name: source_country
        data_type: string
        description: "Country of the source"
      - name: source_customer
        data_type: string
        description: "Customer associated with the source"
      - name: source_cvc_check
        data_type: string
        description: "CVC check result of the source"
      - name: source_dynamic_last4
        data_type: string
        description: "Dynamic last 4 digits of the source"
      - name: source_exp_month
        data_type: integer
        description: "Expiration month of the source"
      - name: source_exp_year
        data_type: integer
        description: "Expiration year of the source"
      - name: source_fingerprint
        data_type: string
        description: "Fingerprint of the source"
      - name: source_funding
        data_type: string
        description: "Funding type of the source"
      - name: source_id
        data_type: string
        description: "ID of the source"
      - name: source_last4
        data_type: string
        description: "Last 4 digits of the source"
      - name: source_name
        data_type: string
        description: "Name in the source"
      - name: source_object
        data_type: string
        description: "Object type of the source"
      - name: source_tokenization_method
        data_type: string
        description: "Tokenization method of the source"
      - name: source_wallet
        data_type: string
        description: "Wallet of the source"
      - name: source_transfer
        data_type: string
        description: "Transfer associated with the source"
      - name: statement_descriptor
        data_type: string
        description: "For card charges, use statement_descriptor_suffix instead Otherwise, you can use this value as the complete description of a charge on your customers’ statements Must contain at least one letter, maximum 22 characters"
      - name: statement_descriptor_suffix
        data_type: string
        description: "Provides information about the charge that customers see on their statements Concatenated with the prefix (shortened descriptor) or statement descriptor that’s set on the account to form the complete statement descriptor Maximum 22 characters for the concatenated descriptor"
      - name: status
        data_type: string
        description: "The status of the payment is either succeeded, pending, or failed"
      - name: transfer_data
        data_type: string
        description: "An optional dictionary including the account to automatically transfer to as part of a destination charge"
      - name: transfer_group
        data_type: string
        description: "A string that identifies this transaction as part of a group"
